## Importing nesessary modules

In [1]:
import numpy as np
import pandas as pd
import itertools

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## Reading the dataset

In [5]:
df = pd.read_pickle("datasets/news.pkl", compression="bz2")
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [3]:
df.shape

(6335, 4)

In [5]:
labels = df.label
labels.head()

0    FAKE
1    FAKE
2    REAL
3    FAKE
4    REAL
Name: label, dtype: object

## Spliting the dataset into training and testing sets

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    df["text"], labels, test_size=0.2, random_state=7
)

## TfidfVectorizer
Let’s initialize a TfidfVectorizer with stop words from the English language and a maximum document frequency of 0.7 (terms with a higher document frequency will be discarded). Stop words are the most common words in a language that are to be filtered out before processing the natural language data. And a TfidfVectorizer turns a collection of raw documents into a matrix of TF-IDF features.

Now, fit and transform the vectorizer on the train set, and transform the vectorizer on the test set.

In [7]:
# Initialize a TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)

# Fit and transform train set, transform test set
tfidf_train = tfidf_vectorizer.fit_transform(X_train)
tfidf_test = tfidf_vectorizer.transform(X_test)

## PassiveAggressiveClassifier

In [15]:
# Initialize a PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=100)
pac.fit(tfidf_train, y_train)

# Predict on the test set and calculate accuracy
y_pred = pac.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(score*100,2)}%")

Accuracy: 93.05%


In [16]:
# Build confusion matrix
confusion_matrix(y_test, y_pred, labels=["FAKE", "REAL"])

array([[592,  46],
       [ 42, 587]], dtype=int64)

In [17]:
print(classification_report(y_test, y_pred, target_names=["FAKE", "REAL"]))

              precision    recall  f1-score   support

        FAKE       0.93      0.93      0.93       638
        REAL       0.93      0.93      0.93       629

    accuracy                           0.93      1267
   macro avg       0.93      0.93      0.93      1267
weighted avg       0.93      0.93      0.93      1267



## LogisticRegressionClassifier

In [19]:
# Initialize a LogisticRegression
lr = LogisticRegression()
lr.fit(tfidf_train, y_train)

# Predict on the test set and calculate accuracy
y_pred = lr.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(score*100,2)}%")

Accuracy: 91.71%


In [20]:
# Build confusion matrix
confusion_matrix(y_test, y_pred, labels=["FAKE", "REAL"])

array([[600,  38],
       [ 67, 562]], dtype=int64)

In [21]:
print(classification_report(y_test, y_pred, target_names=["FAKE", "REAL"]))

              precision    recall  f1-score   support

        FAKE       0.90      0.94      0.92       638
        REAL       0.94      0.89      0.91       629

    accuracy                           0.92      1267
   macro avg       0.92      0.92      0.92      1267
weighted avg       0.92      0.92      0.92      1267



## DecisionTreeClassifier

In [22]:
# Initialize a DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(tfidf_train, y_train)

# Predict on the test set and calculate accuracy
y_pred = dt.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(score*100,2)}%")

Accuracy: 80.11%


In [23]:
# Build confusion matrix
confusion_matrix(y_test, y_pred, labels=["FAKE", "REAL"])

array([[516, 122],
       [130, 499]], dtype=int64)

In [24]:
print(classification_report(y_test, y_pred, target_names=["FAKE", "REAL"]))

              precision    recall  f1-score   support

        FAKE       0.80      0.81      0.80       638
        REAL       0.80      0.79      0.80       629

    accuracy                           0.80      1267
   macro avg       0.80      0.80      0.80      1267
weighted avg       0.80      0.80      0.80      1267



## Random Forest

In [26]:
# Initialize a RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, max_features=None)
rf.fit(tfidf_train, y_train)

# Predict on the test set and calculate accuracy
y_pred = rf.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(score*100,2)}%")

Accuracy: 87.45%


In [27]:
# Build confusion matrix
confusion_matrix(y_test, y_pred, labels=["FAKE", "REAL"])

array([[543,  95],
       [ 64, 565]], dtype=int64)

In [28]:
print(classification_report(y_test, y_pred, target_names=["FAKE", "REAL"]))

              precision    recall  f1-score   support

        FAKE       0.89      0.85      0.87       638
        REAL       0.86      0.90      0.88       629

    accuracy                           0.87      1267
   macro avg       0.88      0.87      0.87      1267
weighted avg       0.88      0.87      0.87      1267

